import { Project } from "@/types";


export const projects: Project[] = [
    {
        title: 'Klasse',
        description: 'Klasse didirikan pada Februari 2022 dengan sebuah misi sederhana: memberdayakan individu untuk berkarya dan meraih mimpi mereka di bidang Arsitektur, Arsitektur Lanskap, Desain Interior, dan Teknik Sipil.',
        technologies: ['MongoDB', 'Express.js', 'React', 'Node.js'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://klasse.id/',
        image: '/projects/klasse.png',
    },
    {
        title: 'Autokit',
        description: 'PT. Jillbert Kreasindo Kurnia, berbasis di Jakarta Utara, adalah pelopor di industri otomotif sebagai holding company yang mengelola sejumlah perusahaan terkemuka.',
        technologies: ['MongoDB', 'Express.js', 'React', 'Node.js'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://autokit.id/',
        image: '/projects/autokit.png',
    },
    {
        title: 'PT REKA SOLUSI ARTHAMEDIA',
        description: 'PT Reka Solusi Arthamedia, merupakan anak perusahaan KOPERASI REKA SEJAHTERA (KOPRES), didirikan pada tanggal 23 Juni 2003.',
        technologies: ['HTML', 'CSS', 'JavaScript', 'PHP'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://ptrsa.co.id/',
        image: '/projects/ptrsa.png',
    },
    {
        title: 'Caiedu',
        description: 'Caiedu adalah sebuah penyedia layanan yang berkomitmen untuk memberikan pendidikan berkualitas tinggi kepada semua individu yang bersemangat untuk belajar dan berkembang.',
        technologies: ['MongoDB', 'Express.js', 'React', 'Node.js'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://caiedu.id/',
        image: '/projects/caiedu.png',
    },
    {
        title: 'Yatekno',
        description: 'Berbekal pengalaman selama 9 tahun, Kami meriset dan melakukan pembahasan secara objektif untuk membantu Kamu membeli produk terbaik',
        technologies: ['MongoDB', 'Express.js', 'React', 'Node.js'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://www.yatekno.com/',
        image: '/projects/yatekno.png',
    },
    {
        title: 'Raja wali mas yodosan',
        description: 'Kisah ini dimulai pada tahun 2001 dalam sebuah laboratorium kecil. Selama lebih dari satu dekade, kami telah melakukan penelitian berkelanjutan untuk menciptakan produk herbal berkualitas terbaik. Tujuan awalnya sebenarnya hanya untuk penggunaan pribadi.',
        technologies: ['HTML', 'CSS', 'JavaScript', 'PHP'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://rajawalimasyodosan.co.id/',
        image: '/projects/rajawalimasyodosan.png',
    },
    {
        title: 'Storesyntax',
        description: 'Store Syntax adalah platform Store Specialist Mobile Legend dengan layanan profesional mulai dari Top-Up Diamond, Paket Joki, Joki New Season, Paket Joki Classic, Joki Montage, Starlight Murah & Gift Kharisma.',
        technologies: ['HTML', 'CSS', 'JavaScript', 'PHP'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://storesyntax.com/',
        image: '/projects/storesyntax.png',
    },
    {
        title: 'Timber Tropics',
        description: 'TimberTropics is a company that is based in Indonesia. Our factory is located in Surabaya, Indonesia. With our skill in making high-quality wooden products, it is no surprise that we are one of the leading manufacturers in the Indonesian wooden tiling market.',
        technologies: ['HTML', 'CSS', 'JavaScript', 'WordPress'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://timbertropics.com/',
        image: '/projects/timbertropics.png',
    },
    {
        title: 'IBIOMASS',
        description: 'PT Industri Biomass Indonesia merupakan perusahaan green energy yang berdiri sejak 2022 , yang di mana kami berfokus pada menghasilkan sumber energi yang tidak merusak lingkungan.',
        technologies: ['HTML', 'CSS', 'JavaScript', 'WordPress'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://ibiomass.id/',
        image: '/projects/ibiomass.png',
    },
    {
        title: 'Luthansa',
        description: 'Kami adalah perusahaan yang bergerak dalam bidang jasa penyewaan Bus Pariwisata. Kami menyewakan Bus Pariwisata mulai dari Commuter Hi-ace 15 seats, Microbus Elf 19/21 seats, Medium bus 31/33 seats, Big Bus 44/48 seats, dan Big Bus 54/59 seat',
        technologies: ['HTML', 'CSS', 'JavaScript', 'WordPress'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://busluthansa.co.id/',
        image: '/projects/busluthansa.png',
    },
    {
        title: 'Rcraft',
        description: 'Kami Rcraft, Perusahaan produksi e-liquid vape terbaik di Indonesia. Sejak 2020, Rcraft terus berinovasi penuh untuk produk e-liquid dengan gaya kekinian yang pastinya cocok untuk semua kawan vapers.',
        technologies: ['HTML', 'CSS', 'JavaScript', 'WordPress'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://rcraft.id/',
        image: '/projects/rcraft.png',
    },
    {
        title: 'PT Epayu Digital Kreatif',
        description: 'PT Epayu Digital Kreatif adalah perusahaan yang bergerak di bidang jasa digital. Menyediakan layanan pengisian Pulsa, paket data internet, voucher game online, PPOB, saldo ewallet, saldo paypal secara online.',
        technologies: ['MongoDB', 'Express.js', 'React', 'Node.js'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://epayu.co.id/',
        image: '/projects/epayu.png',
    },
    {
        title: 'Namirohtour',
        description: 'An Namiroh Travelindo adalah biro umroh dan travel perjalanan wisata yang berkomitmen untuk memberikan pengalaman perjalanan yang tak terlupakan. Dengan izin umroh dan haji yang kami miliki, kami memberikan layanan yang profesional, aman, dan berkualitas kepada para pelanggan kami. Kami berinovasi secara terus-menerus, mengutamakan kepuasan pelanggan, dan menjaga komitmen lingkungan dan sosial.',
        technologies: ['MongoDB', 'Express.js', 'React', 'Node.js'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://namirohtour.com/',
        image: '/projects/namirohtour.png',
    },
    {
        title: 'Chingu Laundry',
        description: 'Chingu Laundry Express adalah layanan laundry kiloan dan satuan. Kami adalah tim profesional yang selalu mengutamakan kualitas cucian & pelayanan dengan prinsip bersih, rapi, wangi, higienis & tepat waktu.',
        technologies: ['Next.js'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://chingu-laundry.com/',
        image: '/projects/chingu-laundry.png',
    },
    {
        title: 'ViaPaypal',
        description: 'ViaPayPal.id menyediakan jasa top up isi saldo PayPal, jual beli saldo PayPal dan jasa pembayaran online dengan rate murah, pengiriman cepat, aman dan terpercaya.',
        technologies: ['MongoDB', 'Express.js', 'React', 'Node.js'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://viapaypal.id/',
        image: '/projects/viapaypal.png',
    },
    {
        title: 'Tokousd',
        description: 'Tokousd.id menyediakan jasa top up, isi saldo PayPal, jasa bayar online menggunakan metode PayPal dengan rate murah, pengiriman cepat, aman dan terpercaya. Dapatkan kurs beli PayPal dengan harga termurah dan tanpa biaya sesuai dengan Syarat dan Ketentuan dari layanan kami.',
        technologies: ['MongoDB', 'Express.js', 'React', 'Node.js'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://tokousd.id/',
        image: '/projects/tokousd.png',
    },
    {
        title: 'Sarang Wisdom',
        description: 'We recognize the limitations of traditional team-building methods and aim to address them through our distinctive approach.',
        technologies: ['HTML', 'CSS', 'JavaScript', 'WordPress'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://sarangwisdom.com/',
        image: '/projects/sarangwisdom.png',
    },
    {
        title: 'Sappe Indonesia Profile',
        description: 'PT Sappe Indonesia is the result of a strategic partnership between Sappe PCL (Thailand) and PT Sappe Indonesia.',
        technologies: ['HTML', 'CSS', 'JavaScript', 'WordPress'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://sappeindonesia.com/',
        image: '/projects/sappeindonesia.png',
    },
    {
        title: 'Saget Design Studio',
        description: 'Book a call with us at Saget and discover how you can transform the way you source design, for good.',
        technologies: ['HTML', 'CSS', 'JavaScript', 'React'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://sagetlab.com/',
        image: '/projects/sagetlab.png',
    },
    {
        title: 'OWL Eyewear Shop',
        description: 'O.W.L is a brand that marries culture of excellence and attention paid to details to create a perfect alchemy between aesthetics and technology. Owl\'s frames are more than just glasses, they are works of art.',
        technologies: ['WordPress', 'WooCommerce', 'PHP', 'MySQL'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://owleyewear.id/',
        image: '/projects/owleyewear.png',
    },
    {
        title: 'Web Developer ID',
        description: 'WEBDEVELOPER.ID adalah mitra terpercaya Anda dalam menghadirkan website berkualitas tinggi untuk menunjang kesuksesan bisnis di era digital. Sebagai perusahaan web developer terkemuka di Indonesia.',
        technologies: ['HTML', 'CSS', 'JavaScript', 'PHP'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://webdeveloper.id/',
        image: '/projects/webdeveloper.png',
    },
    {
        title: 'Diamond Pavilion',
        description: 'Diamond Pavilion hold a humble belief in the celebration of love and its precious moments. Additionally, we firmly believe that diamonds are crafted to enhance every milestone in life.',
        technologies: ['HTML', 'CSS', 'JavaScript', 'WordPress'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://diamondpavilion.id/',
        image: '/projects/diamondpavilion.png',
    },
    {
        title: 'Galva Technologies',
        description: 'Galva Technologies adalah mitra regional yang terkemuka untuk produk elektronik, dengan memasok produk berkualitas tinggi (seperti komputer, printer, display, dan peralatan audio-video) ke beragam klien korporat.',
        technologies: ['HTML', 'CSS', 'JavaScript', 'Bootstrap'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://www.gtc.co.id/id',
        image: '/projects/gtc.png',
    },
    {
        title: 'G-log Logistics',
        description: 'G-Log is a forward-thinking freight forwarder, committed to transforming global cargo movement.',
        technologies: ['HTML', 'CSS', 'JavaScript', 'Bootstrap'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://glog.co.id/',
        image: '/projects/glog.png',
    },
    {
        title: 'Berani Laundry',
        description: 'BERANI adalah merek bisnis laundry yang mengoperasikan jaringan franchise yang sukses di berbagai wilayah.',
        technologies: ['HTML', 'CSS', 'JavaScript', 'WordPress'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://berani-laundry.com/',
        image: '/projects/berani-laundry.png',
    },
    {
        title: 'Klinik Sehat Plus BSD',
        description: 'Klinik kesehatan Sehat Plus BSD menyediakan layanan konsultasi, diagnosis, pengobatan, dan home care oleh tim dokter umum yang terlatih dan berpengalaman dalam menangani berbagai kondisi kesehatan.',
        technologies: ['HTML', 'CSS', 'JavaScript', 'WordPress'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://sehatplusbsd.com/',
        image: '/projects/sehatplusbsd.png',
    },
    {
        title: 'Kepompong Kupu-Kupu',
        description: 'Menyediakan kaftan sarimbit ready stock dengan desain elegan dan nyaman, Kepompong KupuKupu hadir bersama sister brand-nya untuk menghadirkan fashion yang berkelanjutan, penuh keindahan, dan mendukung kerajinan lokal.',
        technologies: ['WordPress', 'WooCommerce', 'CSS', 'JavaScript'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://kepompongkupukupu.id/',
        image: '/projects/kepompongkupukupu.png',
    },
    {
        title: 'Talenta',
        description: 'We are a talent management platform that makes personalized counseling easy for K-12 schools.',
        technologies: ['MongoDB', 'Express.js', 'React', 'Node.js'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://talenta.web.id/',
        image: '/projects/talenta.png',
    },
    {
        title: 'Ecoluxdoors',
        description: 'Ecolux is a bespoke wood door brand established by PT. Bogowonto Primalaras to meet the unique requirements of our partners. We specialize in crafting custom interior and exterior engineered wood doors for projects all over Indonesia and overseas.',
        technologies: ['MongoDB', 'Express.js', 'React', 'Node.js'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://ecoluxdoors.com/',
        image: '/projects/ecoluxdoors.png',
    },
    {
        title: 'ESDIES Dental Home',
        description: 'ESDIES Dental Home didirikan pada 30 Januari 2019 di BSD, Tangerang Selatan, oleh drg. Savedra Pratama, Sp.Pros dan drg. Theresia Dhearine Pratiwi, Sp. KGA.',
        technologies: ['WordPress', 'CSS', 'JavaScript', 'PHP'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://esdiesdentalhome.com/',
        image: '/projects/esdiesdentalhome.png',
    },
    {
        title: 'Synergize Capital',
        description: 'The story of Synergize Capital could be envisioned as a pioneering firm, established with the mission to harness the collaborative power of synergy in the digital technology, particularly within the vibrant and diverse landscape of Indonesian SMEs.',
        technologies: ['MongoDB', 'Express.js', 'React', 'Node.js'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://www.synergizecap.com/',
        image: '/projects/synergizecap.png',
    },
    {
        title: 'Millenial Superfood',
        description: 'Millenial Superfood Indonesia merupakan perusahaan yang berdiri sejak tahun 2022 dan aktif beroperasi secara legal sejak tahun 2023.',
        technologies: ['MongoDB', 'Express.js', 'React', 'Node.js'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://millenialsuperfood.com/',
        image: '/projects/millenialsuperfood.png',
    },
    {
        title: 'E-commerce Platform',
        description: 'A full-stack e-commerce platform built with Next.js, TypeScript, and Tailwind CSS.',
        technologies: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Stripe'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://demo.com',
        image: '/projects/e-commerce-website.png',
      },
      {
        title: 'Task Management App',
        description: 'A collaborative task management application with real-time updates.',
        technologies: ['React', 'Node.js', 'MongoDB', 'Socket.io'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://demo.com',
        image: '/projects/task-manager.webp',
      },
      {
        title: 'Portfolio Website',
        description: 'My personal portfolio website showcasing my projects and skills.',
        technologies: ['Next.js', 'Tailwind CSS', 'Framer Motion'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://demo.com',
        image: '/projects/portfolio-website.jpg',
      },
      {
        title: 'Blog Platform',
        description: 'A blogging platform with user authentication and markdown support.',
        technologies: ['Gatsby', 'GraphQL', 'Contentful'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://demo.com',
        image: '/projects/blog-website.jpeg',
      },
      {
        title: 'Weather App',
        description: 'A weather application that provides real-time weather updates.',
        technologies: ['React', 'OpenWeatherMap API'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://demo.com',
        image: '/projects/weather-app.png',
      },
      {
        title: 'Chat Application',
        description: 'A real-time chat application using WebSocket technology.',
        technologies: ['React', 'Node.js', 'Socket.io'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://demo.com',
        image: '/projects/chat-app.png',
      },
      {
        title: 'Recipe Finder',
        description: 'A recipe search application using the Edamam API.',
        technologies: ['React', 'Edamam API'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://demo.com',
        image: '/projects/recipe-finder.png',
      },
      {
        title: 'Expense Tracker',
        description: 'A personal finance tracker to manage expenses and income.',
        technologies: ['React', 'Firebase'],
        githubLink: 'https://github.com/maulanajs',
        demoLink: 'https://demo.com',
        image: '/projects/expense-tracker.webp',
      }
  ];